import AboutSection from "@/components/Sections/About/AboutSection";
import ContactSection from "@/components/Sections/Contact/ContactSection";
import ProjectsSection from "@/components/Sections/Projects/ProjectsSection";
import SkillsSection from "@/components/Sections/Skills/SkillsSection";
import Head from "next/head";

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className="h-screen grid place-content-center">Main Page</main>
         <AboutSection />
         <SkillsSection />
         <ProjectsSection />
         <ContactSection />
      </>
   );
}
